version: '3.4'

services:
  # nginx:
  #   image: nginx:stable-alphine
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ${PWD}/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:z
  #   networks:
  #     - frontend

  dcarddrawcardfrontend:
    image: dcarddrawcardfrontend
    build:
      context: D4-homework-Frontend
      dockerfile: ./Dockerfile
    command: sh -c "yarn start"
    depends_on:
      - dcarddrawcardbackend
    ports:
      - 3001:3000
    networks:
      - frontend
      - backend

  dcarddrawcardbackend:
    image: dcarddrawcardbackend
    build:
      context: D4-homework-Backend
      dockerfile: ./Dockerfile
    depends_on:
      - redis-server
      - mongo
    command: sh -c "yarn run test && yarn start"
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend

  redis-server:
    image: redis:6.2.1
    ports:
      - 6379:6379
    networks:
      - backend

  mongo:
    image: mongo:4.4.4-bionic
    volumes:
      - ./data:/data/db
    # ports:
    #   - 27017:27017
    networks:
      - backend

networks:
  frontend:
  backend: